name: build release artifacts

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest']
      fail-fast: false
    steps:
      - uses: actions/checkout@v2

      - name: run build
        run: |
          git submodule update --init --recursive
          mkdir build
          cd build && cmake -DCMAKE_BUILD_TYPE=RELEASE ..
          make
          
      - name: run tests
        run: ./build/test/test_suite

      - name: create release artifacts/packages
        run: |
          cd build
          make package
      
      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release-packages
          path: ./build/sqlcheck-x86_64.*